# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.0
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: cd SpanJson
- script: dotnet restore
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: cd ..
- script: dotnet restore -s https://api.nuget.org/v3/index.json -s .\SpanJson\bin\Release
- script: dotnet build -c Release
- script: dotnet test -c Release SpanJson.Tests\SpanJson.Tests.csproj
- script: dotnet test -c Release SpanJson.AspNetCore.Formatter.Tests\SpanJson.AspNetCore.Formatter.Tests.csproj