
using System;
// Autogenerated
// ReSharper disable BuiltInTypeReferenceStyle
namespace SpanJson.Tests
{
			
	public partial class NullableSByteTests : NullableTestBase<SByte>
	{
	}

	public partial class NullableSByteListTests : NullableListTestBase<SByte>
	{
	}

	public partial class NullableSByteArrayTests : NullableArrayTestBase<SByte>
	{
	}
	public partial class SByteTests : TestBase<SByte>
	{
	}

	public partial class SByteListTests : ListTestBase<SByte>
	{
	}

	public partial class SByteArrayTests : ArrayTestBase<SByte>
	{
	}
			
	public partial class NullableInt16Tests : NullableTestBase<Int16>
	{
	}

	public partial class NullableInt16ListTests : NullableListTestBase<Int16>
	{
	}

	public partial class NullableInt16ArrayTests : NullableArrayTestBase<Int16>
	{
	}
	public partial class Int16Tests : TestBase<Int16>
	{
	}

	public partial class Int16ListTests : ListTestBase<Int16>
	{
	}

	public partial class Int16ArrayTests : ArrayTestBase<Int16>
	{
	}
			
	public partial class NullableInt32Tests : NullableTestBase<Int32>
	{
	}

	public partial class NullableInt32ListTests : NullableListTestBase<Int32>
	{
	}

	public partial class NullableInt32ArrayTests : NullableArrayTestBase<Int32>
	{
	}
	public partial class Int32Tests : TestBase<Int32>
	{
	}

	public partial class Int32ListTests : ListTestBase<Int32>
	{
	}

	public partial class Int32ArrayTests : ArrayTestBase<Int32>
	{
	}
			
	public partial class NullableInt64Tests : NullableTestBase<Int64>
	{
	}

	public partial class NullableInt64ListTests : NullableListTestBase<Int64>
	{
	}

	public partial class NullableInt64ArrayTests : NullableArrayTestBase<Int64>
	{
	}
	public partial class Int64Tests : TestBase<Int64>
	{
	}

	public partial class Int64ListTests : ListTestBase<Int64>
	{
	}

	public partial class Int64ArrayTests : ArrayTestBase<Int64>
	{
	}
			
	public partial class NullableByteTests : NullableTestBase<Byte>
	{
	}

	public partial class NullableByteListTests : NullableListTestBase<Byte>
	{
	}

	public partial class NullableByteArrayTests : NullableArrayTestBase<Byte>
	{
	}
	public partial class ByteTests : TestBase<Byte>
	{
	}

	public partial class ByteListTests : ListTestBase<Byte>
	{
	}

	public partial class ByteArrayTests : ArrayTestBase<Byte>
	{
	}
			
	public partial class NullableUInt16Tests : NullableTestBase<UInt16>
	{
	}

	public partial class NullableUInt16ListTests : NullableListTestBase<UInt16>
	{
	}

	public partial class NullableUInt16ArrayTests : NullableArrayTestBase<UInt16>
	{
	}
	public partial class UInt16Tests : TestBase<UInt16>
	{
	}

	public partial class UInt16ListTests : ListTestBase<UInt16>
	{
	}

	public partial class UInt16ArrayTests : ArrayTestBase<UInt16>
	{
	}
			
	public partial class NullableUInt32Tests : NullableTestBase<UInt32>
	{
	}

	public partial class NullableUInt32ListTests : NullableListTestBase<UInt32>
	{
	}

	public partial class NullableUInt32ArrayTests : NullableArrayTestBase<UInt32>
	{
	}
	public partial class UInt32Tests : TestBase<UInt32>
	{
	}

	public partial class UInt32ListTests : ListTestBase<UInt32>
	{
	}

	public partial class UInt32ArrayTests : ArrayTestBase<UInt32>
	{
	}
			
	public partial class NullableUInt64Tests : NullableTestBase<UInt64>
	{
	}

	public partial class NullableUInt64ListTests : NullableListTestBase<UInt64>
	{
	}

	public partial class NullableUInt64ArrayTests : NullableArrayTestBase<UInt64>
	{
	}
	public partial class UInt64Tests : TestBase<UInt64>
	{
	}

	public partial class UInt64ListTests : ListTestBase<UInt64>
	{
	}

	public partial class UInt64ArrayTests : ArrayTestBase<UInt64>
	{
	}
			
	public partial class NullableSingleTests : NullableTestBase<Single>
	{
	}

	public partial class NullableSingleListTests : NullableListTestBase<Single>
	{
	}

	public partial class NullableSingleArrayTests : NullableArrayTestBase<Single>
	{
	}
	public partial class SingleTests : TestBase<Single>
	{
	}

	public partial class SingleListTests : ListTestBase<Single>
	{
	}

	public partial class SingleArrayTests : ArrayTestBase<Single>
	{
	}
			
	public partial class NullableDoubleTests : NullableTestBase<Double>
	{
	}

	public partial class NullableDoubleListTests : NullableListTestBase<Double>
	{
	}

	public partial class NullableDoubleArrayTests : NullableArrayTestBase<Double>
	{
	}
	public partial class DoubleTests : TestBase<Double>
	{
	}

	public partial class DoubleListTests : ListTestBase<Double>
	{
	}

	public partial class DoubleArrayTests : ArrayTestBase<Double>
	{
	}
			
	public partial class NullableBooleanTests : NullableTestBase<Boolean>
	{
	}

	public partial class NullableBooleanListTests : NullableListTestBase<Boolean>
	{
	}

	public partial class NullableBooleanArrayTests : NullableArrayTestBase<Boolean>
	{
	}
	public partial class BooleanTests : TestBase<Boolean>
	{
	}

	public partial class BooleanListTests : ListTestBase<Boolean>
	{
	}

	public partial class BooleanArrayTests : ArrayTestBase<Boolean>
	{
	}
			
	public partial class NullableCharTests : NullableTestBase<Char>
	{
	}

	public partial class NullableCharListTests : NullableListTestBase<Char>
	{
	}

	public partial class NullableCharArrayTests : NullableArrayTestBase<Char>
	{
	}
	public partial class CharTests : TestBase<Char>
	{
	}

	public partial class CharListTests : ListTestBase<Char>
	{
	}

	public partial class CharArrayTests : ArrayTestBase<Char>
	{
	}
			
	public partial class NullableDateTimeTests : NullableTestBase<DateTime>
	{
	}

	public partial class NullableDateTimeListTests : NullableListTestBase<DateTime>
	{
	}

	public partial class NullableDateTimeArrayTests : NullableArrayTestBase<DateTime>
	{
	}
	public partial class DateTimeTests : TestBase<DateTime>
	{
	}

	public partial class DateTimeListTests : ListTestBase<DateTime>
	{
	}

	public partial class DateTimeArrayTests : ArrayTestBase<DateTime>
	{
	}
			
	public partial class NullableDateTimeOffsetTests : NullableTestBase<DateTimeOffset>
	{
	}

	public partial class NullableDateTimeOffsetListTests : NullableListTestBase<DateTimeOffset>
	{
	}

	public partial class NullableDateTimeOffsetArrayTests : NullableArrayTestBase<DateTimeOffset>
	{
	}
	public partial class DateTimeOffsetTests : TestBase<DateTimeOffset>
	{
	}

	public partial class DateTimeOffsetListTests : ListTestBase<DateTimeOffset>
	{
	}

	public partial class DateTimeOffsetArrayTests : ArrayTestBase<DateTimeOffset>
	{
	}
			
	public partial class NullableTimeSpanTests : NullableTestBase<TimeSpan>
	{
	}

	public partial class NullableTimeSpanListTests : NullableListTestBase<TimeSpan>
	{
	}

	public partial class NullableTimeSpanArrayTests : NullableArrayTestBase<TimeSpan>
	{
	}
	public partial class TimeSpanTests : TestBase<TimeSpan>
	{
	}

	public partial class TimeSpanListTests : ListTestBase<TimeSpan>
	{
	}

	public partial class TimeSpanArrayTests : ArrayTestBase<TimeSpan>
	{
	}
			
	public partial class NullableGuidTests : NullableTestBase<Guid>
	{
	}

	public partial class NullableGuidListTests : NullableListTestBase<Guid>
	{
	}

	public partial class NullableGuidArrayTests : NullableArrayTestBase<Guid>
	{
	}
	public partial class GuidTests : TestBase<Guid>
	{
	}

	public partial class GuidListTests : ListTestBase<Guid>
	{
	}

	public partial class GuidArrayTests : ArrayTestBase<Guid>
	{
	}
	public partial class StringTests : TestBase<String>
	{
	}

	public partial class StringListTests : ListTestBase<String>
	{
	}

	public partial class StringArrayTests : ArrayTestBase<String>
	{
	}
			
	public partial class NullableDecimalTests : NullableTestBase<Decimal>
	{
	}

	public partial class NullableDecimalListTests : NullableListTestBase<Decimal>
	{
	}

	public partial class NullableDecimalArrayTests : NullableArrayTestBase<Decimal>
	{
	}
	public partial class DecimalTests : TestBase<Decimal>
	{
	}

	public partial class DecimalListTests : ListTestBase<Decimal>
	{
	}

	public partial class DecimalArrayTests : ArrayTestBase<Decimal>
	{
	}
	public partial class VersionTests : TestBase<Version>
	{
	}

	public partial class VersionListTests : ListTestBase<Version>
	{
	}

	public partial class VersionArrayTests : ArrayTestBase<Version>
	{
	}
	public partial class UriTests : TestBase<Uri>
	{
	}

	public partial class UriListTests : ListTestBase<Uri>
	{
	}

	public partial class UriArrayTests : ArrayTestBase<Uri>
	{
	}
}