using System;

// Autogenerated
// ReSharper disable BuiltInTypeReferenceStyle
namespace SpanJson.Tests
{
    public class NullableSByteTests : NullableTestBase<SByte>
    {
    }

    public class NullableSByteListTests : NullableListTestBase<SByte>
    {
    }

    public class NullableSByteArrayTests : NullableArrayTestBase<SByte>
    {
    }

    public class SByteTests : TestBase<SByte>
    {
    }

    public class SByteListTests : ListTestBase<SByte>
    {
    }

    public class SByteArrayTests : ArrayTestBase<SByte>
    {
    }

    public class NullableInt16Tests : NullableTestBase<Int16>
    {
    }

    public class NullableInt16ListTests : NullableListTestBase<Int16>
    {
    }

    public class NullableInt16ArrayTests : NullableArrayTestBase<Int16>
    {
    }

    public class Int16Tests : TestBase<Int16>
    {
    }

    public class Int16ListTests : ListTestBase<Int16>
    {
    }

    public class Int16ArrayTests : ArrayTestBase<Int16>
    {
    }

    public class NullableInt32Tests : NullableTestBase<Int32>
    {
    }

    public class NullableInt32ListTests : NullableListTestBase<Int32>
    {
    }

    public class NullableInt32ArrayTests : NullableArrayTestBase<Int32>
    {
    }

    public class Int32Tests : TestBase<Int32>
    {
    }

    public class Int32ListTests : ListTestBase<Int32>
    {
    }

    public class Int32ArrayTests : ArrayTestBase<Int32>
    {
    }

    public class NullableInt64Tests : NullableTestBase<Int64>
    {
    }

    public class NullableInt64ListTests : NullableListTestBase<Int64>
    {
    }

    public class NullableInt64ArrayTests : NullableArrayTestBase<Int64>
    {
    }

    public class Int64Tests : TestBase<Int64>
    {
    }

    public class Int64ListTests : ListTestBase<Int64>
    {
    }

    public class Int64ArrayTests : ArrayTestBase<Int64>
    {
    }

    public class NullableByteTests : NullableTestBase<Byte>
    {
    }

    public class NullableByteListTests : NullableListTestBase<Byte>
    {
    }

    public class NullableByteArrayTests : NullableArrayTestBase<Byte>
    {
    }

    public class ByteTests : TestBase<Byte>
    {
    }

    public class ByteListTests : ListTestBase<Byte>
    {
    }

    public class ByteArrayTests : ArrayTestBase<Byte>
    {
    }

    public class NullableUInt16Tests : NullableTestBase<UInt16>
    {
    }

    public class NullableUInt16ListTests : NullableListTestBase<UInt16>
    {
    }

    public class NullableUInt16ArrayTests : NullableArrayTestBase<UInt16>
    {
    }

    public class UInt16Tests : TestBase<UInt16>
    {
    }

    public class UInt16ListTests : ListTestBase<UInt16>
    {
    }

    public class UInt16ArrayTests : ArrayTestBase<UInt16>
    {
    }

    public class NullableUInt32Tests : NullableTestBase<UInt32>
    {
    }

    public class NullableUInt32ListTests : NullableListTestBase<UInt32>
    {
    }

    public class NullableUInt32ArrayTests : NullableArrayTestBase<UInt32>
    {
    }

    public class UInt32Tests : TestBase<UInt32>
    {
    }

    public class UInt32ListTests : ListTestBase<UInt32>
    {
    }

    public class UInt32ArrayTests : ArrayTestBase<UInt32>
    {
    }

    public class NullableUInt64Tests : NullableTestBase<UInt64>
    {
    }

    public class NullableUInt64ListTests : NullableListTestBase<UInt64>
    {
    }

    public class NullableUInt64ArrayTests : NullableArrayTestBase<UInt64>
    {
    }

    public class UInt64Tests : TestBase<UInt64>
    {
    }

    public class UInt64ListTests : ListTestBase<UInt64>
    {
    }

    public class UInt64ArrayTests : ArrayTestBase<UInt64>
    {
    }

    public class NullableSingleTests : NullableTestBase<Single>
    {
    }

    public class NullableSingleListTests : NullableListTestBase<Single>
    {
    }

    public class NullableSingleArrayTests : NullableArrayTestBase<Single>
    {
    }

    public class SingleTests : TestBase<Single>
    {
    }

    public class SingleListTests : ListTestBase<Single>
    {
    }

    public class SingleArrayTests : ArrayTestBase<Single>
    {
    }

    public class NullableDoubleTests : NullableTestBase<Double>
    {
    }

    public class NullableDoubleListTests : NullableListTestBase<Double>
    {
    }

    public class NullableDoubleArrayTests : NullableArrayTestBase<Double>
    {
    }

    public class DoubleTests : TestBase<Double>
    {
    }

    public class DoubleListTests : ListTestBase<Double>
    {
    }

    public class DoubleArrayTests : ArrayTestBase<Double>
    {
    }

    public class NullableBooleanTests : NullableTestBase<Boolean>
    {
    }

    public class NullableBooleanListTests : NullableListTestBase<Boolean>
    {
    }

    public class NullableBooleanArrayTests : NullableArrayTestBase<Boolean>
    {
    }

    public class BooleanTests : TestBase<Boolean>
    {
    }

    public class BooleanListTests : ListTestBase<Boolean>
    {
    }

    public class BooleanArrayTests : ArrayTestBase<Boolean>
    {
    }

    public class NullableCharTests : NullableTestBase<Char>
    {
    }

    public class NullableCharListTests : NullableListTestBase<Char>
    {
    }

    public class NullableCharArrayTests : NullableArrayTestBase<Char>
    {
    }

    public class CharTests : TestBase<Char>
    {
    }

    public class CharListTests : ListTestBase<Char>
    {
    }

    public class CharArrayTests : ArrayTestBase<Char>
    {
    }

    public class NullableDateTimeTests : NullableTestBase<DateTime>
    {
    }

    public class NullableDateTimeListTests : NullableListTestBase<DateTime>
    {
    }

    public class NullableDateTimeArrayTests : NullableArrayTestBase<DateTime>
    {
    }

    public class DateTimeTests : TestBase<DateTime>
    {
    }

    public class DateTimeListTests : ListTestBase<DateTime>
    {
    }

    public class DateTimeArrayTests : ArrayTestBase<DateTime>
    {
    }

    public class NullableDateTimeOffsetTests : NullableTestBase<DateTimeOffset>
    {
    }

    public class NullableDateTimeOffsetListTests : NullableListTestBase<DateTimeOffset>
    {
    }

    public class NullableDateTimeOffsetArrayTests : NullableArrayTestBase<DateTimeOffset>
    {
    }

    public class DateTimeOffsetTests : TestBase<DateTimeOffset>
    {
    }

    public class DateTimeOffsetListTests : ListTestBase<DateTimeOffset>
    {
    }

    public class DateTimeOffsetArrayTests : ArrayTestBase<DateTimeOffset>
    {
    }

    public class NullableTimeSpanTests : NullableTestBase<TimeSpan>
    {
    }

    public class NullableTimeSpanListTests : NullableListTestBase<TimeSpan>
    {
    }

    public class NullableTimeSpanArrayTests : NullableArrayTestBase<TimeSpan>
    {
    }

    public class TimeSpanTests : TestBase<TimeSpan>
    {
    }

    public class TimeSpanListTests : ListTestBase<TimeSpan>
    {
    }

    public class TimeSpanArrayTests : ArrayTestBase<TimeSpan>
    {
    }

    public class NullableGuidTests : NullableTestBase<Guid>
    {
    }

    public class NullableGuidListTests : NullableListTestBase<Guid>
    {
    }

    public class NullableGuidArrayTests : NullableArrayTestBase<Guid>
    {
    }

    public class GuidTests : TestBase<Guid>
    {
    }

    public class GuidListTests : ListTestBase<Guid>
    {
    }

    public class GuidArrayTests : ArrayTestBase<Guid>
    {
    }

    public class StringTests : TestBase<String>
    {
    }

    public class StringListTests : ListTestBase<String>
    {
    }

    public class StringArrayTests : ArrayTestBase<String>
    {
    }

    public class NullableDecimalTests : NullableTestBase<Decimal>
    {
    }

    public class NullableDecimalListTests : NullableListTestBase<Decimal>
    {
    }

    public class NullableDecimalArrayTests : NullableArrayTestBase<Decimal>
    {
    }

    public class DecimalTests : TestBase<Decimal>
    {
    }

    public class DecimalListTests : ListTestBase<Decimal>
    {
    }

    public class DecimalArrayTests : ArrayTestBase<Decimal>
    {
    }

    public class VersionTests : TestBase<Version>
    {
    }

    public class VersionListTests : ListTestBase<Version>
    {
    }

    public class VersionArrayTests : ArrayTestBase<Version>
    {
    }

    public class UriTests : TestBase<Uri>
    {
    }

    public class UriListTests : ListTestBase<Uri>
    {
    }

    public class UriArrayTests : ArrayTestBase<Uri>
    {
    }
}